### ISSUE TITLE
Minor refactoring

### ISSUE THREAD

**Issue by yana-safonova** [yana-safonova/ig_repertoire_constructor#10]
Refactoring of prefix tree code

**Comment by eodus** [comment]
Я сделал много мелких изменений с тех пор, но рефакторить там можно еще много и долго. Однако, Trie объективно самая простая (и смая "школьная") часть алгоритма и рефакторить впервую очередь надо, я думаю, не ее

**Comment by yana-safonova** [comment]
Забей пока на него) Просто кажется, мы как-то посмотрели на тот код и решили повесить этот таск)
