### ISSUE TITLE
Починить гермлайны или объяснить как их готовить

### ISSUE THREAD

**Issue by yana-safonova** [yana-safonova/ig_repertoire_constructor#13]
На ветке ig_rep_con_2.0 запуск 
 ./ig_repertoire_constructor_2.0.py -s test_dataset/IGHV1-8.fastq -o oppa
ig_kplus_vj_finder падает с ошибкой 
/home/yana/gitrep/ig_repertoire_constructor/ext/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type seqan::FileOpenError: Could not open file ./germline/human/IGHV.fa)

**Comment by eodus** [comment]
параметр --db-directory, пофиксили уже
