### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by suntaosimon** [yana-safonova/ig_repertoire_constructor#138]
follow the manual and tried to install igRec but failed, please help.
Downloaded the zip file, and unzipped in my mac. cd into that unzipped folder, 
type:
    ./prepare_cfg

following error came:
10:yana-safonova-ig_repertoire_constructor-ee478f7 mac$ ./prepare_cfg
-bash: ./prepare_cfg: No such file or directory
10:yana-safonova-ig_repertoire_constructor-ee478f7 mac$ 

Also,

 ./igrec.py --test
ERROR: Binary file of Pair reads merging was not found

Probably you forgot to prepare IgReC. Please follow instructions:
  (1) remove build/ directory
  (2) type command './prepare cfg' to check all dependencies
  (3) type 'make' to compile IgReC
  (4) rerun IgReC

**Comment by yana-safonova** [comment]
Hi suntaosimon, 

Thank you for the report! We changed installation procedure, but forgot to update manual. 

For IgReC installation, just type 
`make`

**Comment by suntaosimon** [comment]
Thanks for your reply. I have tried `make` but still has some errors. 

mkdir -p build/release
cd build/release && cmake ../.. -DCMAKE_BUILD_TYPE=""RelWithAsserts"" -DCMAKE_INSTALL_PREFIX="/usr/local" -Wno-dev
/bin/sh: cmake: command not found
make: *** [cmake] Error 127

**Comment by suntaosimon** [comment]
forgot to install cMake. Installed successfully now.
