### ISSUE TITLE
Риды из test_dataset/IGHV1-8.fastq не соединяются ребром из-за неправильного кропа

### ISSUE THREAD

**Issue by yana-safonova** [yana-safonova/ig_repertoire_constructor#14]
634171_merged_read_MISEQ2:53:000000000-A2BMV:1:2111:12528:4183_1:N:0:TTAGGC и 
488483_merged_read_MISEQ2:53:000000000-A2BMV:1:2105:13655:16079_1:N:0:TTAGGC

**Comment by eodus** [comment]
Как выяснилось, кроп тут правильный, но при заполнении отрезанного начала второго рида туда вставляеются нуклеотиды из гермлайна. А первый рид как раз в одном из первых нуклеотидов отличается от гермлайна. Таким образом, расстояние между ридами не 3, а 4
