### ISSUE TITLE
Параметры сборки вынести в main-скрипт

### ISSUE THREAD

**Issue by eodus** [yana-safonova/ig_repertoire_constructor#17]
У нас появилось куча мелких параметров микротулов
1) Тип цепи(цепей)
2) Набор генов (использовать ли псевдогены)
3) Количество коррекируемых нуклеотидов в начале и отбрасываемых в хвосте
4) Что-то еще, что я забыл

Думаю, что стоит сделать их параметрами командной строки главного скрипта (скрытыми, разумеется) с разумными (текущими) дефолтами.

**Comment by yana-safonova** [comment]
Сделала первые два пункта + --organism входными нескрытыми опциями:
e31d9fcaf656e8af45d11134c0933b651118d27a

**Comment by yana-safonova** [comment]
не вижу, какой опцией в ig_kplus_vj_finder контролируется 3й пункт

**Comment by eodus** [comment]
left-fill-germline и right-cropped
Возможно, названия не самые удачные, поменять можно тут:
            ("left-fill-germline", po::value<int>(&left_fill_germline)->default_value(left_fill_germline),
             "the number left positions which will be filled by germline")
            ("right-cropped", po::value<size_t>(&num_cropped_nucls)->default_value(num_cropped_nucls),
             "the number of right positions which will be cropped")

**Comment by yana-safonova** [comment]
Предлагаю пока понизить приоритет у задач, не связанных с внешним юзабилити
- после релиза разберемся

2015-09-18 1:01 GMT+03:00 Alexander Shlemov notifications@github.com:

> left-fill-germline и right-cropped
> Возможно, названия не самые удачные, поменять можно тут:
> ("left-fill-germline",
> po::value(&left_fill_germline)->default_value(left_fill_germline),
> "the number left positions which will be filled by germline")
> ("right-cropped",
> po::value(&num_cropped_nucls)->default_value(num_cropped_nucls),
> "the number of right positions which will be cropped")
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yana-safonova/ig_repertoire_constructor/issues/17#issuecomment-141243951
> .

## 

Yana Safonova,
Research Scientist,
Algorithmic Biology Laboratory, Saint Petersburg Academic University RAS
Center for Algorithmic Biotechnology, Saint Petersburg State University
http://bioinf.spbau.ru/members/yana-safonova
