### ISSUE TITLE
trie compressor падает, если входной файл пустой 

### ISSUE THREAD

**Issue by yana-safonova** [yana-safonova/ig_repertoire_constructor#18]
На тесте:
./ig_repertoire_constructor.py --test --no-pseudogenes -C kappa

**Comment by eodus** [comment]
Яна, пинг-понг. Теперь падает на поиске клик)

**Comment by yana-safonova** [comment]
Accepted :)

On Friday, September 18, 2015, Alexander Shlemov notifications@github.com
wrote:

> Яна, пинг-понг. Теперь падает на поиске клик)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yana-safonova/ig_repertoire_constructor/issues/18#issuecomment-141241360
> .

## 

Yana Safonova,
Research Scientist,
Algorithmic Biology Laboratory, Saint Petersburg Academic University RAS
Center for Algorithmic Biotechnology, Saint Petersburg State University
http://bioinf.spbau.ru/members/yana-safonova

**Comment by yana-safonova** [comment]
Ты не поверишь, теперь упал consensus constructor :)

**Comment by eodus** [comment]
fixed in e477187
