### ISSUE TITLE
Fancy build and install

### ISSUE THREAD

**Issue by eodus** [yana-safonova/ig_repertoire_constructor#30]
- implement all build and install logic via cmake; get rid of ad-hoc build scripts
- make "debug" build optional, users shouldn't even know about it
- check (again) MacOS build
- implement installation in system or user-specified directory
- check DEB/RPM autopackaging (using checkinstall) or make package by some another way
- update all dependences and remove obsolete ones
- (optionally) check Windows compatibility
- (optionally) check x32-compatibility
- add git commit hashcode as version to binaries
- [get rid of prepare script](https://github.com/yana-safonova/ig_repertoire_constructor/issues/42)

deep courtesy to @asl

**Comment by yana-safonova** [comment]
Саша, разбей эту мегатаску на маленькие и закрой ее. Например, компиляция под мак уже есть. Пункт убрать prepare cfg дублируется с другим issue. На 32 compatibility & compilation for Windows надо просто вбить, на мой взгляд.

**Comment by eodus** [comment]
The most of these (except Win and 32 compatibility) was implemented in 45ee017195d43eea322fccacdb28be22706bd5d1
