### ISSUE TITLE
DSF fails to call `migec` in case of running not from IGRC root dir

### ISSUE THREAD

**Issue by eodus** [yana-safonova/ig_repertoire_constructor#31]
Пофиксить DSF, чтобы он мог находить migec в этом случае. Сейчас он всегда ищет его по относительному пути build/release/bin/migec

**Comment by yana-safonova** [comment]
Ты имеешь в виду Metis? Ок, завтра пофикшу.

On Monday, 12 October 2015, Alexander Shlemov notifications@github.com
wrote:

> Пофиксить DSF, чтобы он мог находить migec в этом случае. Сейчас он всегда
> ищет его по относительному пути build/release/bin/migec
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yana-safonova/ig_repertoire_constructor/issues/31.

## 

Yana Safonova,
Research Scientist
Center for Algorithmic Biotechnology, Saint Petersburg State University
Algorithmic Biology Laboratory, Saint Petersburg Academic University RAS
http://bioinf.spbau.ru/members/yana-safonova

**Comment by yana-safonova** [comment]
fix: 6dc5a658592478f1581dd719d4030b760438cb93

12 октября 2015 г., 1:31 пользователь Yana Safonova <safonova.yana@gmail.com

> написал:
> 
> Ты имеешь в виду Metis? Ок, завтра пофикшу.
> 
> On Monday, 12 October 2015, Alexander Shlemov notifications@github.com
> wrote:
> 
> > Пофиксить DSF, чтобы он мог находить migec в этом случае. Сейчас он
> > всегда ищет его по относительному пути build/release/bin/migec
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/yana-safonova/ig_repertoire_constructor/issues/31.
> 
> ## 
> 
> Yana Safonova,
> Research Scientist
> Center for Algorithmic Biotechnology, Saint Petersburg State University
> Algorithmic Biology Laboratory, Saint Petersburg Academic University RAS
> http://bioinf.spbau.ru/members/yana-safonova

## 

Yana Safonova,
Research Scientist
Center for Algorithmic Biotechnology, Saint Petersburg State University
Algorithmic Biology Laboratory, Saint Petersburg Academic University RAS
http://bioinf.spbau.ru/members/yana-safonova
