### ISSUE TITLE
Добавить информацию в VJ Finder

### ISSUE THREAD

**Issue by yana-safonova** [yana-safonova/ig_repertoire_constructor#36]
Хочется также видеть информацию о позициях начала и конца выравнивания для последовательностей генов - она сейчас нужна для VDJ labeling. Еще предлагаю убрать запятые и оставить только space-separators, а то в плюсах не очень удобно парсить CSV файлик...

**Comment by eodus** [comment]
Already done. Separator is controlled by cmd arg for now.
Alignment info added and removed again =)
