### ISSUE TITLE
Make cmake make without prepare

### ISSUE THREAD

**Issue by Chushuhuch** [yana-safonova/ig_repertoire_constructor#42]

**Comment by eodus** [comment]
Что было сделано по этому вопросу (0b70eff77e7ca14bf8c1a14beb542ca4302c0f31)
1. Питоновские файлы, необходимые для работы констрактора, перенесены в py
2. Добавлен глобальный cmakelist, который самодостаточен (копировние конфигов и прочее он теперь делает сам)
3. Его можно скормить Клену, и Клен будет нормально его собирать (больше не используются волшебные скрипты, которые Клен вызвать не может). Клену передавать именно главный CmakeList.txt из корня, а не тот, который в src
4. Главный (и единственный) Makefile теперь сам умеет создавать папочку для билда
5. Появился таргет make install. Теперь наш тул можно УСТАНОВИТЬ (make install prefix=PREFIX). Установится в каталог PREFIX/igrec. По дефолту prefix=/opt
6. sudo checkinstall установит тул в систему пакетом (и даже положит симлинк в /usr/bin, можно запускать тул из любого места по igrec.py)
7. По мелочи почищены левые файлы в треке

Просьба это затестить (особенно меня мак волнует) и можно влить, я считаю, что это все нелишний функционал

P.S. Мейкфайл в корне сделан для удобства. Реально можно все собрать и без него чистым cmake'ом.
P.P.S. В следующей серии будет сборка деб-пакетом, пока я на это вбил. Пока есть только УСТАНОВКА пакетом (это не одно и то же, пакет, который собирается checkinstall'ом может иметь проблемы с переносимостью на другие машины)
P.P.P.S. Делать make install от рута не надо, он установит тул, но не обернет его в пакет. Потом придется удалять его руками. Если хочется заинсталлить локально, то надо делать make install prefix=~/my_cool_tools. Для локальной инсталляции рута не надо (симлинка тоже не будет=)

**Comment by yana-safonova** [comment]
В целом выглядит круто, у меня есть несколько комментариев.
1. Правильно я поняла, что по дефолту igrec будет устанавливаться не в текущую директорию, а в /opt? Если так, то это не очень удобно. Или можно тупо запустить make и все соберется прямо в текущей папке?
2. Makefile удалять не надо, потому что его удобно использовать для дебага конкретного проекта.
3. На маке проверю, напишу, что получилось.

**Comment by eodus** [comment]
1. Да, make (без install) соберет проект как и раньше
2. Да, я сам привык собирать make'ом, поэтому оставил
3. Спасибо =)

**Comment by eodus** [comment]
Этот патч был заброшен и потом переделан. Теперь влит в основную ветку 45ee017195d43eea322fccacdb28be22706bd5d1
