### ISSUE TITLE
Рефакторинг matcher & graph constructor

### ISSUE THREAD

**Issue by yana-safonova** [yana-safonova/ig_repertoire_constructor#8]
Улучшить переиспользование кода, уменьшить кол-во инделов, избежать повторное выравнивание

**Comment by eodus** [comment]
Не помню, что такое повторное выравнивание(

**Comment by yana-safonova** [comment]
Мне кажется, это уже давно закрыли. Там где-то было повторное выравнивание при построении графа

**Comment by eodus** [comment]
Closed as stale issue.
